"""Execution choices absent from the clips, displayed before the owner enables orders.

Each line says whether it restates a video rule or is an app interpretation.
A changed version requires the owner to re-review before entries resume.
"""
POLICY_VERSION = 'nasdaq-qqq-execution-v7-video-aligned'
POLICY = {
    'version': POLICY_VERSION,
    'instrument': 'QQQ',
    'summary': [
        'Trade QQQ, an ETF tracking the Nasdaq-100; it is not Nasdaq futures. The recording marks Nasdaq futures on a continuous session; QQQ regular-session candles are the app translation.',
        'Evaluate both primary entry methods separately: a four-hour area with an hourly break and return to the level, or a sweep of a previous-day extreme. QQQ uses completed regular-session hourly candles.',
        'Four-hour areas (video: mark everywhere price "has broken through or touched more than once" on the four-hour chart, a handful of hand-drawn lines). App interpretation: candidates are confirmed four-hour swing highs and lows, each a ±0.1% band; candidates within 0.2% of an existing candidate merge into one cluster; an area is established at its second nonadjacent interaction (the pivot itself counts as the first; a later candle touching the band or closing across it counts as another) and its bounds then freeze; at most the 16 established areas nearest the current price are watched. Four-hour areas now include the afternoon (13:30–16:00) bucket. Previous-day high and low are exact levels from the previous session.',
        'Break and retest (video: "we break and we trade the retest"): a completed hourly close through an area edge is the break; the event confirms when a later hourly candle returns to the broken edge, whatever that candle closes. The trade direction is not the break direction: it is whatever the leaders and VIX support, as in the recording\'s short at a level price just reclaimed. A close through the far edge invalidates the event; a fresh crossing starts a new one.',
        'An opportunity lives until the end of the next regular session after its break or sweep (two sessions, the origin\'s included), so the retest can arrive the following day; the overnight session boundary is not a gap, but a missing hourly candle inside a session invalidates the event. Only one entry is allowed for that opportunity, even if a later retest or leader direction changes. The lifetime is an app choice: the video states no limit and shows retests days after the break. After the retest a plan exists only while the latest completed hourly candle still touches the event area or closes within 0.4% of it (video: "we are near a pivotal area"); once price leaves, the event waits for another return to the level instead of entering away from it. The 0.4% proximity is an app choice.',
        'Use genuine five-minute leader candles. Leader areas are the five-minute repeated-interaction bands plus period levels computed from each leader\'s own data, as the video\'s key-levels indicator plots them: previous-session high, low and close, the session open, previous-week high, low and mid, the current week\'s Monday session high and low, the week open, the month open and the session VWAP, each a ±0.1% band established when the figure became known. Sessions inside the seven-session five-minute window use their regular-session five-minute candles; older sessions (previous week, month open) use the provider\'s daily candles, and a failed daily read keeps the last validated ones. The vote reports which area it came from. The indicator\'s supply and demand boxes are not reproduced.',
        'At least four of seven leaders must agree, with at most one opposing (video: majority buying → long, majority selling → short, mixed → no trade); a company with no reaction is neutral. This count is the owner-selected app interpretation; the videos do not specify a number.',
        'A leader reaction can begin on any five-minute candle of the current session, including before the Nasdaq event, and remains valid for up to 60 minutes while the latest close stays beyond its area boundary in the vote direction; a small pullback that stays beyond the area keeps the vote. A close back through the area drops it. All seven latest observations must share a completed candle time; missing candles block confirmation. A company with conflicting reactions at different areas is neutral (the video says to skip mixed evidence); it neither votes nor blocks the others. Expired evidence cannot authorize an entry between analysis updates.',
        'The hourly and four-hour Nasdaq overview describes confirmed swing structure. It is context, not an additional entry requirement or a forecast. A candidate trade may oppose the earlier Nasdaq break direction, as illustrated in the primary recording.',
        'Actual VIX must react in the opposite direction at one of its own pre-existing areas, using completed 15-minute candles (video: "look left" two or three days to where VIX previously pivoted or based, then wait for it to start buying for a Nasdaq short). App interpretation: areas are ±1% bands around repeated earlier swing extremes (about 0.3 index points wide at VIX 15) plus consolidation bases, any run of at least four consecutive 15-minute candles whose combined range is within 2% of price; the reaction may sit on either of the last two closed candles of the current session, provided no later close crossed back through the area and the latest close is still beyond it. Futures, CFDs and volatility ETFs are not substitutes.',
        'Actual VIX candles come from InsightSentry Free, refreshed after completed 15-minute periods. A current actual-index quote is required before entry; a still-current cached quote retains its original source timestamp.',
        'The free data allowance has a durable request limit. Missing candles, delayed data, an exhausted allowance or an unsuccessful quote check blocks new entries. Candle and quote recovery is time-based within the free allowance: a late candle or a failed quote check becomes eligible for another request after a fixed wait, instead of a fixed number of attempts per period, so a delayed publication cannot block entries for the rest of that 15-minute period.',
        'Each strategy may attempt two new entries per New York session: two for Socrates on QQQ and two for the crypto range reversal, no longer one shared budget. An attempt counts when an order is sent, whether or not it fills. This session limit is an app discipline rule inspired by the creator\'s two-trade challenge, not a rule the videos state numerically.',
        'No new QQQ entries in the final 30 minutes of the regular session; the closing exit starts five minutes before the close. Both are app choices so that a late entry is never flattened moments later.',
        'Buy the saved dollar amount, with the planned purchase within 1% below the target.',
        'Short setups are executed by buying PSQ, the ProShares inverse (−1x) Nasdaq-100 ETF, with the stop and target translated by the same percentage distances, measured from the live QQQ bid at entry to the QQQ stop and target levels; this is an instrument translation because the account cannot short. PSQ tracks −1x the DAILY move of the Nasdaq-100 and is held intraday only.',
        'Stop beyond the event area, the originating and confirming candles and the current candle. Take profit at the nearest opposing pre-existing 4-hour or previous-day level that is at least as far away as the stop distance (a minimum of 1R); pre-existing means established before the entry candle began, so a retest on the session after the break can target the break day\'s high and low and its afternoon four-hour areas; the swept area itself is never the target, and a nearer level below that multiple is skipped for the next one. The stop distance must be at least 0.1% of the entry price. If no level qualifies there is no trade. The videos never show a stop, target or size; the 1R minimum, the minimum stop distance and the level geometry are app choices. One position at a time.',
        'Broker stop orders are placed after entry fills. Targets and end-of-day exits require the host machine to remain running and connected. Fractional stops expire each day.',
        'A rejected or unconfirmed QQQ order pauses the Socrates strategy only, with a visible notice; global Live money and the crypto strategy continue. Unconfirmed stop protection has a persistent 30-second acceptance deadline; nonworking protection pauses Socrates entries and starts cancellation-safe recovery. Unknown cancellation or broker state requires owner review and cannot authorize a competing sale.',
        'Off stops new entries and cancels unfinished entries; existing positions continue their exits. Fills, slippage and profits are not guaranteed.',
    ],
}
