"""Execution choices absent from the clips, displayed before the owner enables orders.

Each line says whether it restates a video rule or is an app interpretation.
A changed version requires the owner to re-review before entries resume.
"""
POLICY_VERSION = 'nasdaq-qqq-execution-v6-reward-risk-vix-persistence'
POLICY = {
    'version': POLICY_VERSION,
    'instrument': 'QQQ',
    'summary': [
        'Trade QQQ, an ETF tracking the Nasdaq-100; it is not Nasdaq futures.',
        'Evaluate both primary entry methods separately: a four-hour area with an hourly break/retest, or a sweep of a previous-day extreme. QQQ uses completed regular-session hourly candles.',
        'The recordings do not define the colored areas numerically. App interpretation: fixed 0.1% bands around historical price anchors, confirmed by two nonadjacent touches or crossings; four-hour Nasdaq areas and five-minute leader areas.',
        'Use genuine five-minute leader candles. At least five of seven leaders must agree, with at most one opposing. This participation threshold is the owner-selected app interpretation; the videos do not specify a numeric count.',
        'A leader reaction can begin on any five-minute candle of the current session, including before the Nasdaq event, and remains valid for up to 15 minutes while the latest close stays beyond its area boundary in the vote direction; a small pullback that stays beyond the area keeps the vote. A close back through the area drops it. All seven latest observations must share a completed candle time; missing candles block confirmation. A company with conflicting reactions at different areas is neutral (the video says to skip mixed evidence); it neither votes nor blocks the others. Expired evidence cannot authorize an entry between analysis updates.',
        'The hourly and four-hour Nasdaq overview describes confirmed swing structure. It is context, not an additional entry requirement or a forecast. A candidate trade may oppose the earlier Nasdaq break direction, as illustrated in the primary recording.',
        'An opportunity expires 180 minutes after its original break or sweep, or at the session change. Only one entry is allowed for that opportunity, even if a later retest or leader direction changes. These timing rules are app choices, not numerical rules supplied by the creator.',
        'Actual VIX must react in the opposite direction at one of its own pre-existing repeated pivot areas, using completed 15-minute candles. App interpretation: areas are ±1% bands around earlier swing extremes (about 0.3 index points wide at VIX 15); the reaction may sit on either of the last two closed candles of the current session, provided no later close crossed back through the area and the latest close is still beyond it. Futures, CFDs and volatility ETFs are not substitutes.',
        'Actual VIX candles come from InsightSentry Free, refreshed after completed 15-minute periods. A current actual-index quote is required before entry; a still-current cached quote retains its original source timestamp.',
        'The free data allowance has a durable request limit. Missing candles, delayed data, an exhausted allowance or an unsuccessful quote check blocks new entries. Candle and quote recovery is time-based within the free allowance: a late candle or a failed quote check becomes eligible for another request after a fixed wait, instead of a fixed number of attempts per period, so a delayed publication cannot block entries for the rest of that 15-minute period.',
        'Each strategy may attempt two new entries per New York session: two for Socrates on QQQ and two for the crypto range reversal, no longer one shared budget. An attempt counts when an order is sent, whether or not it fills. This session limit is an app discipline rule inspired by the creator\'s two-trade challenge, not a rule the videos state numerically.',
        'No new QQQ entries in the final 30 minutes of the regular session; the closing exit starts five minutes before the close. Both are app choices so that a late entry is never flattened moments later.',
        'Buy the saved dollar amount, with the planned purchase within 1% below the target. Shorts require whole shares within 1% of that amount, account permission and borrow availability. Small fractional targets cannot open shorts; on this cash account short setups are skipped and reported.',
        'Stop beyond the event area, the originating and confirming candles and the current candle. Take profit at the nearest opposing pre-existing 4-hour or previous-day level that is at least as far away as the stop distance (a minimum of 1R); the swept area itself is never the target, and a nearer level below that multiple is skipped for the next one. The stop distance must be at least 0.1% of the entry price. If no level qualifies there is no trade. The videos mention the next pivotal area qualitatively; the 1R minimum, the minimum stop distance and the level geometry are app choices. One position at a time.',
        'Broker stop orders are placed after entry fills. Targets and end-of-day exits require the host machine to remain running and connected. Fractional stops expire each day.',
        'A rejected or unconfirmed QQQ order pauses the Socrates strategy only, with a visible notice; global Live money and the crypto strategy continue. Unconfirmed stop protection has a persistent 30-second acceptance deadline; nonworking protection pauses Socrates entries and starts cancellation-safe recovery. Unknown cancellation or broker state requires owner review and cannot authorize a competing sale.',
        'Off stops new entries and cancels unfinished entries; existing positions continue their exits. Fills, slippage and profits are not guaranteed.',
    ],
}
